### PR TITLE
Fix #10: Use symfony http-client and respect proxy settings

### LINKED ISSUE #10: SelfUpdateCommand.php does not use proxy settings in the stream context
I'm behind a proxy and the `self-update` command breaks because it does not take my proxy environment variables into consideration when checking github for the latest release in this file: https://github.com/consolidation/self-update/blob/ed68ed69a427a03bb6fd2197e6d3d564a5ce0cba/src/SelfUpdateCommand.php#L55

Specifically I'm getting this error when trying to `self-update` Acquia CLI:
```
PHP Warning:  file_get_contents(https://api.github.com/repos/acquia/cli/releases): failed to open stream: Connection refused
in phar:///usr/local/bin/acli/vendor/consolidation/self-update/src/SelfUpdateCommand.php on line 70

Warning: file_get_contents(https://api.github.com/repos/acquia/cli/releases): failed to open stream: Connection refused in phar:///usr/local/bin/acli/vendor/consolidation/self-update/src/SelfUpdateCommand.php on line 70

In SelfUpdateCommand.php line 74:

  API error - no release found at GitHub repository acquia/cli

self:update [--stable] [--preview]
```

I think something needs to be added to check for proxy settings and apply them to the stream context, if necessary, but I'm not quite sure how to access proxy settings in this script:
```
$opts = [
            'http' => [
                'method' => 'GET',
                'proxy' => $proxy_environment_variable,
                'header' => [
                    'User-Agent: ' . $this->applicationName  . ' (' . $this->gitHubRepository . ')' . ' Self-Update (PHP)'
                ]
            ]
        ];
```

### PR DESCRIPTION
**Pull request by danepowell**
Fixes #10

### CODE REVIEW

**Comment by danepowell** [comment]
I have no way to verify that the proxy settings actually work, but I did at least verify there are no regressions.

File: src/SelfUpdateCommand.php [hunk 1]
```diff
@@ -75,26 +76,27 @@ protected function configure(): void
...
+        $response = $client->request(
+            'GET',
+            'https://api.github.com/repos/' . $this->gitHubRepository . '/releases'
+        );
 
-        $context = stream_context_create($opts);
-
-        $releases = file_get_contents('https://api.github.com/repos/' . $this->gitHubRepository . '/releases', false, $context);
-        $releases = json_decode($releases);
+        $releases = json_decode($response->getContent(), FALSE, 512, JSON_THROW_ON_ERROR);
```
Comment (lyrixx) [inline src/SelfUpdateCommand.php:99]: You could use `$response->toArray()`
ref: https://github.com/symfony/symfony/blob/99b25a1a9de655961ac7c8fbf18e5d00f84ed798/src/Symfony/Contracts/HttpClient/ResponseInterface.php#L61-L72

Comment (danepowell) [reply src/SelfUpdateCommand.php:99]: Thanks, but the rest of the class assumes `$releases` is an object and I wanted to minimize refactoring for this PR
